export const bossPool = [
    {
        id: 1,
        main: {
            name: '异齿猛兽首领',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 25,
            shieldArmor: 0,
            maxStacks: 0,
            tags: ['重甲', '生物', '重型', '异形'],
            passive: ['异形甲壳'],
        },
        minions: [
            {
                name: '异齿猛兽',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 20,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '重型', '异形'],
                passive: ['异形甲壳'],
            },
        ]
    },
    {
        id: 2,
        main: {
            name: '寒冰王蛇',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 6,
            shieldArmor: 0,
            maxStacks: 0,
            tags: ['重甲', '生物', '惧热', '重型', '异形'],
            passive: ['冰霜环绕', '冰霜进化', '冰悚嚎叫'],
        },
        minions: [
            {
                name: '冰蛇',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 4,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['生物', '惧热', '异形'],
                passive: ['冰霜回复', '冰霜进化'],
            },
        ]
    },
    {
        id: 3,
        main: {
            name: '莽兽',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 8,
            shieldArmor: 0,
            maxStacks: 0,
            tags: ['重甲', '生物', '重型', '异形'],
            passive: ['应激甲壳II', '求生本能II', '冷适应'],
        },
        minions: [
            {
                name: '狂暴畸变体',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 5,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '重型', '异形'],
                passive: ['应激甲壳I', '求生本能I', '冷适应'],
            },
            {
                name: '剧毒畸变体',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 7,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '重型', '异形'],
                passive: ['应激甲壳I', '求生本能I', '冷适应'],
            },
        ]
    },
    {
        id: 4,
        main: {
            name: '空间站感染虫',
            type: '主宰',
            maxHP: 20000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 5,
            shieldArmor: 0,
            maxStacks: 0,
            tags: ['重甲', '生物', '机械', '异形'],
            passive: ['感染空间站', '病毒云', '霉菌滋生'],
        },
        minions: [
            {
                name: '机械感染虫',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 4,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '机械', '异形'],
                passive: ['病毒云', '霉菌滋生'],
            },
            {
                name: '空间站哨枪塔',
                type: '子代',
                maxHP: 30000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 6.5,
                shieldArmor: 0,
                maxStacks: 10,
                tags: ['重甲', '机械', '建筑'],
                passive: ['岗哨机枪', '结构装甲'],
            },
        ]
    },
    {
        id: 5,
        main: {
            name: '吸血蝙蝠首领',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 2.5,
            shieldArmor: 0,
            maxStacks: 20,
            tags: ['生物', '异形'],
            passive: ['吸血唾液', '进食', '吐血', '嗜血狂暴'],
        },
        minions: [
            {
                name: '吸血蝙蝠',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 2.5,
                shieldArmor: 0,
                maxStacks: 20,
                tags: ['生物', '异形'],
                passive: ['吸血唾液', '进食', '吐血'],
            },
        ]
    },
    {
        id: 6,
        main: {
            name: '亚电主宰者',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 1000,
            armor: 4,
            shieldArmor: 0,
            maxStacks: 0,
            tags: ['护盾', '灵能', '重型', '异形'],
            passive: ['超导体', '能源虹吸', '电能冲击波', '电能立场', '脉冲', '能量黑洞'],
        },
        minions: [
            {
                name: '亚电能者',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 4,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['护盾', '灵能', '异形'],
                passive: ['超导体', '能量虹吸', '能量黑洞'],
            },
        ]
    },
    {
        id: 7,
        main: {
            name: '烈焰庞兽',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 20,
            shieldArmor: 0,
            maxStacks: 20,
            tags: ['重甲', '生物', '惧寒', '重型', '异形'],
            passive: ['火焰异形', '庞兽狂暴', '灼烧粘液', '炼狱爆弹', '火焰吐息', '太阳耀斑'],
        },
        minions: [
            {
                name: '火焰甲虫',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 15,
                shieldArmor: 0,
                maxStacks: 20,
                tags: ['重甲', '生物', '惧寒', '异形'],
                passive: ['火焰异形', '灼烧粘液', '腐蚀胆汁', '燃烧潜地'],
            },
        ]
    },
    {
        id: 8,
        main: {
            name: '狂猎猛禽首领',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 3,
            shieldArmor: 0,
            maxStacks: 0,
            tags: ['生物', '异形'],
            passive: ['猎手异形', '致命一击', '狂暴', '伪装'],
        },
        minions: [
            {
                name: '狂猎猛禽1',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 2.5,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['生物', '异形'],
                passive: ['猎手异形', '狂暴', '伪装'],
            },
            {
                name: '狂猎猛禽2',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 2.5,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['生物', '异形'],
                passive: ['猎手异形', '狂暴', '伪装'],
            },
        ]
    },
    {
        id: 9,
        main: {
            name: '宇宙界主',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 1000,
            armor: 2,
            shieldArmor: 0,
            maxStacks: 50,
            tags: ['重甲', '生物', '灵能', '异形'],
            passive: ['宇宙能量', '复苏', '光影之刃', '远古预兆', '星界之风', '超视距穿梭'],
        },
        minions: [
            {
                name: '宇宙战将',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 1,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '灵能', '异形'],
                passive: ['心灵狂热', '星界之风'],
            },
        ]
    },
    {
        id: 10,
        main: {
            name: '猛毒异兽',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 4,
            shieldArmor: 0,
            maxStacks: 20,
            tags: ['生物', '异形'],
            passive: ['毒性唾液', '剧毒狂暴', '毒气波', '淬毒撕咬', '酸蚀池', '剧毒突袭'],
        },
        minions: [
            {
                name: '剧毒蝙蝠',
                type: '子代',
                maxHP: 10000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 3,
                shieldArmor: 0,
                maxStacks: 20,
                tags: ['轻甲', '生物', '异形'],
                passive: ['毒性唾液', '毒气波', '淬毒撕咬', '酸蚀池'],
            },
        ]
    },
    {
        id: 11,
        main: {
            name: '虫群女王',
            type: '主宰',
            maxHP: 20000,
            maxShield: 0,
            maxEnergy: 0,
            armor: 5,
            shieldArmor: 0,
            maxStacks: 20,
            tags: ['生物', '灵能', '异形'],
            passive: ['虫巢思维', '爆虫伏击', '虚弱喷吐', '治愈虫群', '释放信息素', '恐吓尖啸'],
        },
        minions: [
            {
                name: '孵化场',
                type: '子代',
                maxHP: 30000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 4,
                shieldArmor: 0,
                maxStacks: 20,
                tags: ['重甲', '生物', '建筑', '异形'],
                passive: ['孵化'],
            },
            {
                name: '巢穴雷兽',
                type: '子代',
                maxHP: 5000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 15,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '异形'],
                passive: [],
            },
            {
                name: '巢穴战士',
                type: '子代',
                maxHP: 3000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 4,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['轻甲', '生物', '异形'],
                passive: [],
            },
            {
                name: '巢穴甲虫',
                type: '子代',
                maxHP: 4000,
                maxShield: 0,
                maxEnergy: 0,
                armor: 10,
                shieldArmor: 0,
                maxStacks: 0,
                tags: ['重甲', '生物', '异形'],
                passive: [],
            },
        ]
    },
    {
        id: 12,
        main: {
            name: '坏兄弟',
            type: '主宰',
            maxHP: 30000,
            maxShield: 0,
            maxEnergy: 1000,
            armor: 3,
            shieldArmor: 0,
            maxStacks: 100,
            tags: ['生物', '异形'],
            passive: ['基因变异'],
        },
        minions: [

        ]
    },
]