export const Tasklist = {
  '伽马辐射': {
    id: 1,
    type: '可重复任务',
    target: 1,
    price: 50,
    redCrystalCost: 0,
    condition: '使用【伽马枪】攻击目标并成功增加其1层[辐射]',
  },
  '绝对零度': {
    id: 2,
    type: '可重复任务',
    target: 1,
    price: 75,
    redCrystalCost: 0,
    condition: '使用【零度之下】攻击目标并成功增加其1层[寒冷]',
  },
  '胆汁引爆': {
    id: 3,
    type: '可重复任务',
    target: 1,
    price: 200,
    redCrystalCost: 0,
    condition: '使用【焚烧枪】或【龙息霰弹枪】引爆具有10层及以上[灼烧粘液]的目标',
  },
  '脉冲干扰': {
    id: 4,
    type: '可重复任务',
    target: 1,
    price: 45,
    redCrystalCost: 0,
    condition: '使用【脉冲扰乱枪】攻击目标并成功减少其1层技能层数',
  },
  '能量消耗': {
    id: 5,
    type: '可重复任务',
    target: 1,
    price: 40,
    redCrystalCost: 0,
    condition: '使用【弧焊枪】或【DG-3电弧步枪】攻击目标并成功消耗其100能量',
  },
  '破甲先锋': {
    id: 6,
    type: '可重复任务',
    target: 1,
    price: 80,
    redCrystalCost: 0,
    condition: '使用【M4AE脉冲步枪】或【动力钻头】攻击目标并成功削减其0.1护甲',
  },
  '烈火燎原': {
    id: 7,
    type: '可重复任务',
    target: 1,
    price: 25,
    redCrystalCost: 0,
    condition: '使用【焚烧枪】或【龙息霰弹枪】攻击目标或对目标使用【莫洛托夫燃烧弹】并成功增加其1层[燃烧]',
  },
} as const