// 在武器配置部分添加
export const weaponConfig = {
  // 武器配置
  '高斯步枪': {
    id: 1,
    type: '实弹武器',
    category: '实弹武器',
    level: 1,
    damage: 13,
    armorDamageReduction: 1,  // 每点护甲减伤1点伤害
    description: '标准配置武器，中距离作战利器',
    specialeffect: '',
    price: 100,
    redCrystalCost: 1,
    isantiair: true,
    tagEffects: {
      '轻甲': 1.5,  // 对轻甲目标造成150%伤害
    },
  },
  '激光步枪': {
    id: 2,
    type: '能量武器',
    category: '能量武器',
    level: 1,
    damage: 23,
    armorDamageReduction: 0,
    description: '先进激光武器，远距离精准打击',
    specialeffect: '',
    price: 300,
    redCrystalCost: 3,
    isantiair: true,
    tagEffects: {
      '重甲': 1.5,
    },
  },
  '焚烧枪': {
    id: 3,
    type: '热能武器',
    category: '热能武器',
    level: 1,
    damage: 23,
    armorDamageReduction: 0.25,
    description: '基于热能的强大武器，烧烬一切',
    specialeffect: '攻击时为目标附加1层[燃烧]效果，每层使目标受到火焰伤害时额外造成1点伤害（至多额外造成100点伤害）',
    price: 450,
    redCrystalCost: 4,
    isantiair: false,
    tagEffects: {
      '惧热': 1.5,
      '生物': 1.2,
      '护盾': 0.5,
    },
  },
  '碎骨步枪': {
    id: 4,
    type: '能量武器',
    category: '能量武器',
    level: 2,
    damage: 28,
    armorDamageReduction: 0,
    description: '由激光步枪改良而来，高效的对重甲武器',
    specialeffect: '',
    price: 850,
    redCrystalCost: 8,
    isantiair: true,
    tagEffects: {
      '重甲': 1.75,
    },
  },
  '等离子切割机': {
    id: 5,
    type: '实弹武器',
    category: '实弹武器',
    level: 1,
    damage: 16,
    armorDamageReduction: 1,
    description: '一种改造后的采矿切割机，有效对抗重甲目标',
    specialeffect: '',
    price: 150,
    redCrystalCost: 1,
    isantiair: true,
    tagEffects: {
      '建筑': 2,
      '重甲': 1.5,
      '机械': 1.2,
    },
  },
  '突击霰弹枪': {
    id: 6,
    type: '实弹武器',
    category: '实弹武器',
    level: 1,
    damage: 48,
    armorDamageReduction: 4,
    description: '近距离攻击武器，专为遭遇战设计使用',
    specialeffect: '',
    price: 325,
    redCrystalCost: 3,
    isantiair: false,
    tagEffects: {
      '轻甲': 1.5,
    },
  },
  '侦察步枪': {
    id: 7,
    type: '实弹武器',
    category: '实弹武器',
    level: 2,
    damage: 60,
    armorDamageReduction: 3,
    description: '用于隐秘射击的最佳武器，但是无法穿透护甲',
    specialeffect: '',
    price: 550,
    redCrystalCost: 5,
    isantiair: true,
    tagEffects: {

    },
  },
  '零度之下': {
    id: 8,
    type: '热能武器',
    category: '热能武器',
    level: 2,
    damage: 25,
    armorDamageReduction: 1,
    description: '喷射稳定的液氮恒流，对长时间接触者造成致命的损伤',
    specialeffect: '攻击时为目标附加[寒冷]效果，每层使目标受到的伤害提高1%（最多提高100%）',
    price: 775,
    redCrystalCost: 7,
    isantiair: false,
    tagEffects: {
      '惧寒': 1.5,
      '灵能': 1.2,
      '护盾': 0.5,
    },
  },
  '弧焊枪': {
    id: 9,
    type: '能量武器',
    category: '能量武器',
    level: 2,
    damage: 24,
    armorDamageReduction: 0.5,
    description: '一种经过改造的电动工具，可对近距离的目标放出高压电',
    specialeffect: '每次攻击消耗目标200点能量值',
    price: 750,
    redCrystalCost: 7,
    isantiair: true,
    tagEffects: {
      '机械': 2,
      '建筑': 1.5,
    },
  },
  '伽马枪': {
    id: 10,
    type: '热能武器',
    category: '热能武器',
    level: 2,
    damage: 27,
    armorDamageReduction: 0.75,
    description: '一种高度危险性的武器，设计用辐射照射并伤害敌人',
    specialeffect: '攻击无[机械]标签的[生物]目标时附加[辐射]效果，每层使目标的护甲值减少0.05',
    price: 825,
    redCrystalCost: 8,
    isantiair: true,
    tagEffects: {
      '生物': 1.2,
      '机械': 0.2,
    },
  },
  '中子步枪': {
    id: 11,
    type: '能量武器',
    category: '能量武器',
    level: 3,
    damage: 27,
    armorDamageReduction: 0,
    description: '激光步枪的变种，采用折射技术升级',
    specialeffect: '攻击触发散射，对次要目标造成120%基础伤害',
    price: 1450,
    redCrystalCost: 14,
    isantiair: true,
    tagEffects: {
      '灵能': 1.2,
    },
  },
  '粒子相位枪': {
    id: 12,
    type: '能量武器',
    category: '能量武器',
    level: 3,
    damage: 29,
    armorDamageReduction: 0.75,
    description: '面对护盾目标而开发的武器',
    specialeffect: '对[护盾]目标无视50%伤害减免',
    price: 1050,
    redCrystalCost: 10,
    isantiair: true,
    tagEffects: {
      '护盾': 1.75,
    },
  },
  '动力钻头': {
    id: 13,
    type: '实弹武器',
    category: '实弹武器',
    level: 3,
    damage: 32,
    armorDamageReduction: 0.5,
    description: '这种强大的钻头是由那些想把矿工SCV上的大螺丝用作武器的人创造的',
    specialeffect: '',
    price: 1000,
    redCrystalCost: 10,
    isantiair: true,
    tagEffects: {
      '建筑': 2,
      '重甲': 1.5,
      '机械': 1.2,
    },
  },
  '脉冲扰乱枪': {
    id: 14,
    type: '能量武器',
    category: '能量武器',
    level: 3,
    damage: 36,
    armorDamageReduction: 1,
    description: '一种原型能量武器，能够发射强大的脉冲',
    specialeffect: '攻击减少目标2层技能层数',
    price: 1500,
    redCrystalCost: 15,
    isantiair: true,
    tagEffects: {

    },
  },
  'MK79榴弹发射器': {
    id: 15,
    type: '热能武器',
    category: '热能武器',
    level: 4,
    damage: 60,
    armorDamageReduction: 0.5,
    description: '发射非常坚固的专属榴弹，对具有坚固防御的目标几乎没有效果',
    specialeffect: '',
    price: 2000,
    redCrystalCost: 20,
    isantiair: true,
    tagEffects: {
      '重甲': 1.5,
      '轻甲': 0.8,
      '护盾': 0.8,
    },
  },
  'EC13电浆步枪': {
    id: 16,
    type: '能量武器',
    category: '能量武器',
    level: 4,
    damage: 64,
    armorDamageReduction: 4,
    description: '用于解决高生命值目标的次时代武器，擅长对付护盾耗尽或没有护甲的敌人',
    specialeffect: '',
    price: 1750,
    redCrystalCost: 17,
    isantiair: true,
    tagEffects: {
      '生物': 1.2,
      '护盾': 0.5,
    },
  },
  '聚变磁轨枪': {
    id: 17,
    type: '能量武器',
    category: '能量武器',
    level: 4,
    damage: 60,
    armorDamageReduction: 0,
    description: '一种实验性的超级武器，能造成巨大的伤害',
    specialeffect: '',
    price: 1550,
    redCrystalCost: 15,
    isantiair: true,
    tagEffects: {

    },
  },
  'M134轮转机枪': {
    id: 18,
    type: '实弹武器',
    category: '实弹武器',
    level: 5,
    damage: 70,
    armorDamageReduction: 0.1,
    description: '二十一世纪的武器，经过修改以减少后坐力并提高远程精度',
    specialeffect: '连续攻击叠加[横冲直撞]效果，每层提高2.5%伤害（至多提高50%伤害）',
    price: 2000,
    redCrystalCost: 20,
    isantiair: true,
    tagEffects: {
      '轻甲': 1.5,
    },
  },
  '星灼灵焰炮': {
    id: 19,
    type: '能量武器',
    category: '能量武器',
    level: 5,
    damage: 35,
    armorDamageReduction: 1,
    description: '这是在一位高级灵能者的帮助下，解析灵能力量制作出的高科技武器',
    specialeffect: '',
    price: 1550,
    redCrystalCost: 15,
    isantiair: true,
    tagEffects: {
      '机械': 2,
      '建筑': 2,
      '异形': 2,
    },
  },








  '外星电浆': {
    id: 101,
    type: '能量武器',
    category: '传奇武器',
    level: 6,
    damage: 88,
    armorDamageReduction: 3,
    description: '一件传奇武器',
    specialeffect: '',
    price: 6400,
    redCrystalCost: 200,
    isantiair: true,
    tagEffects: {
      '生物': 1.75,
      '护盾': 0.5,
    },
  },
  'MK-4激光步枪': {
    id: 102,
    type: '能量武器',
    category: '传奇武器',
    level: 6,
    damage: 80,
    armorDamageReduction: -1,
    description: '一件传奇武器',
    specialeffect: '暴击率提高25%；连续3次未暴击时，下次攻击必定暴击',
    price: 6400,
    redCrystalCost: 200,
    isantiair: true,
    tagEffects: {
      '重甲': 1.5,
    },
  },
  '龙息霰弹枪': {
    id: 103,
    type: '实弹武器',
    category: '传奇武器',
    level: 6,
    damage: 90,
    armorDamageReduction: 0,
    description: '这是传说中的武器',
    specialeffect: '造成的20%伤害转化为火焰伤害；攻击时为目标附加2层[燃烧]效果，每层使目标受到火焰伤害时额外造成1点伤害（至多额外造成100点伤害）',
    price: 6400,
    redCrystalCost: 200,
    isantiair: false,
    tagEffects: {
      '惧热': 2,
      '轻甲': 1.5,
      '生物': 1.2,
    },
  },
  'DSR-55反器材步枪': {
    id: 104,
    type: '实弹武器',
    category: '传奇武器',
    level: 6,
    damage: 125,
    armorDamageReduction: -2,
    description: '一件传奇武器',
    specialeffect: '',
    price: 6400,
    redCrystalCost: 200,
    isantiair: true,
    tagEffects: {
      '重甲': 1.2,
    },
  },
  '光剑': {
    id: 105,
    type: '能量武器',
    category: '传奇武器',
    level: 6,
    damage: 100,
    armorDamageReduction: 0,
    description: '优雅而独特的武器',
    specialeffect: '无视目标100%伤害减免',
    price: 6400,
    redCrystalCost: 200,
    isantiair: false,
    tagEffects: {

    },
  },
  'DG-3电弧步枪': {
    id: 106,
    type: '能量武器',
    category: '传奇武器',
    level: 6,
    damage: 100,
    armorDamageReduction: 1,
    description: '一件传奇武器',
    specialeffect: '攻击触发散射，对次要目标造成50%基础伤害；每次攻击消耗目标500点能量值',
    price: 6400,
    redCrystalCost: 200,
    isantiair: true,
    tagEffects: {
      '机械': 1.5,
    },
  },
  'M4AE脉冲步枪': {
    id: 107,
    type: '能量武器',
    category: '传奇武器',
    level: 6,
    damage: 80,
    armorDamageReduction: 0,
    description: '一件传奇武器',
    specialeffect: '无法暴击；无视50%伤害减免；每次攻击削减目标0.2护甲值；每次攻击时有33%的概率发射脉冲榴弹，额外造成50%伤害',
    price: 6400,
    redCrystalCost: 200,
    isantiair: true,
    tagEffects: {
      '重甲': 1.2,
    },
  },
  '核聚变重炮': {
    id: 108,
    type: '能量武器',
    category: '传奇武器',
    level: 6,
    damage: 90,
    armorDamageReduction: 0,
    description: '一件传奇武器',
    specialeffect: '无法暴击；每次攻击时有20%的概率造成核爆，额外造成50%的伤害',
    price: 6400,
    redCrystalCost: 200,
    isantiair: true,
    tagEffects: {
      '建筑': 2,
      '重型': 1.5,
      '重甲': 1.2,
    },
  },
}




export const modConfig = {
  '动能增幅': {
    cost: 1750,
    effect: '伤害提高15%',  // 规范术语
    exclusiveTo: '',
    isExclusive: false,
    recyclable: true
  },
  '棱镜水晶': {
    cost: 2050,
    effect: '暴击率提升10%',  // 保持原描述
    exclusiveTo: '',
    isExclusive: false,
    recyclable: true
  },
  '破甲模块': {
    cost: 1250,
    effect: '无视目标10%伤害减免',  // 术语统一
    exclusiveTo: '',
    isExclusive: false,
    recyclable: true
  },
  // 专属模组修改
  '裂甲核心': {
    cost: 750,
    effect: '伤害提高40%，无视目标40%伤害减免',
    exclusiveTo: '高斯步枪',
    isExclusive: true,
    recyclable: false
  },
  '棱镜超载核心': {
    cost: 2250,
    effect: '暴击率提升20%；连续4次未暴击时，下次攻击必定暴击',
    exclusiveTo: '激光步枪',
    isExclusive: true,
    recyclable: false
  },
  '助燃核心': {
    cost: 2550,
    effect: '对[惧热]目标改为造成300%伤害，对[生物]目标改为造成200%伤害；攻击时每1点护甲改为增加0.5点伤害；双倍叠加[燃烧]层数',
    exclusiveTo: '焚烧枪',
    isExclusive: true,
    recyclable: false
  },
  '光束曲射晶片': {
    cost: 2750,
    effect: '攻击触发散射，对次要目标造成100%基础伤害',
    exclusiveTo: '碎骨步枪',
    isExclusive: true,
    recyclable: false
  },
  '金刚石瞄准镜': {
    cost: 2250,
    effect: '无视目标20%伤害减免',
    exclusiveTo: '侦察步枪',
    isExclusive: true,
    recyclable: false
  },
  '微型聚变核心': {
    cost: 2750,
    effect: '连续攻击叠加[聚变]效果，每层提高10%伤害（最多6层）',
    exclusiveTo: '聚变磁轨枪',
    isExclusive: true,
    recyclable: false
  },
  '辐射充能核心': {
    cost: 1750,
    effect: '双倍叠加[辐射]层数，对[生物]目标改为造成150%伤害',
    exclusiveTo: '伽马枪',
    isExclusive: true,
    recyclable: false
  },
  '等离子轴承': {
    cost: 3000,
    effect: '每层[横冲直撞]提供双倍伤害',
    exclusiveTo: 'M134轮转机枪',
    isExclusive: true,
    recyclable: false
  },
  '脉冲稳定核心': {
    cost: 2500,
    effect: '攻击减少目标双倍技能层数',
    exclusiveTo: '脉冲扰乱枪',
    isExclusive: true,
    recyclable: false
  },
  '高压电池': {
    cost: 2250,
    effect: '攻击消耗目标双倍能量值',
    exclusiveTo: '弧焊枪',
    isExclusive: true,
    recyclable: false
  },
  '氮气压缩核心': {
    cost: 2000,
    effect: '双倍叠加[寒冷]层数；攻击时每1点护甲改为减少0点伤害',
    exclusiveTo: '零度之下',
    isExclusive: true,
    recyclable: false
  },
  '轻型电源节点': {
    cost: 1250,
    effect: '伤害提高40%；攻击时每1点护甲改为减少0点伤害',
    exclusiveTo: '等离子切割机',
    isExclusive: true,
    recyclable: false
  },
  '强力钻刺核心': {
    cost: 1750,
    effect: '攻击时每1点护甲改为减少0.2点伤害；每次攻击削减目标0.1护甲值',
    exclusiveTo: '动力钻头',
    isExclusive: true,
    recyclable: false
  },
}

